---
name: Test nle PyPI package
on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [released]
jobs:
  test_install:
    name: Test install
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false
    steps:
    - name: Setup Python ${{ matrix.python-version }} env
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Ensure latest pip, wheel & setuptools
      run: "python -m pip install -q --upgrade pip wheel setuptools"
    - name: Install dependencies
      run: |
        brew install cmake
    - name: Install nle via pip
      run: "pip install nle"
    - name: Check nethack is installed
      run: |
        python -c 'import nle; import gymnasium as gym; e = gym.make("NetHack-v0"); e.reset(); e.step(0)'
        